version: '3'

services:
  frontend:
    env_file:
      - ./.env
    build: ./frontend_app
    image: frontend-app
    environment:
      - FRONTEND_IP=$FRONTEND_IP     
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    volumes:
      - ./frontend_app:/usr/share/nginx/html    
    networks:
      - frontend_backend_network
    depends_on:
      - backend-app

  backend:
    env_file:
      - ./.env
    image: backend-app
    environment:
      - BACKEND_IP=$BACKEND_IP
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    networks:
      - frontend_backend_network

networks:
  frontend_backend_network:
    driver: bridge